### ISSUE TITLE
プラグインの追加インストールが必要でした。

### ISSUE THREAD

**Issue by biatunky** [jaws-ug-tohoku/hands-on_mobileapp#4]
サンプルアプリのプロジェクトを開いた後にプラグインの追加とアップデートが要求されました。

<img width="515" alt="2016-10-27 17 09 27" src="https://cloud.githubusercontent.com/assets/6056801/19763083/90e8cc90-9c77-11e6-9092-49482d62e71a.png">
<img width="799" alt="2016-10-27 17 08 01" src="https://cloud.githubusercontent.com/assets/6056801/19763080/90e2efd2-9c77-11e6-88cf-a5e2eadbf94a.png">
<img width="800" alt="2016-10-27 17 07 02" src="https://cloud.githubusercontent.com/assets/6056801/19763082/90e5c856-9c77-11e6-911f-8a59fe5ba4f2.png">
<img width="1259" alt="2016-10-27 17 06 25" src="https://cloud.githubusercontent.com/assets/6056801/19763081/90e58710-9c77-11e6-8445-0ca5d67a4645.png">

**Comment by Todate** [comment]
資料に追記しました。
